export const t = {
  ink: 'var(--tt-ink)',
  inkSoft: 'var(--tt-ink-soft)',
  teal: 'var(--tt-teal)',
  tealBright: 'var(--tt-teal-bright)',
  amber: 'var(--tt-amber)',
  danger: 'var(--tt-danger)',
  dangerSoft: 'var(--tt-danger-soft)',
  success: 'var(--tt-success)',
  successSoft: 'var(--tt-success-soft)',
  info: 'var(--tt-info)',
  infoSoft: 'var(--tt-info-soft)',
  canvas: 'var(--tt-canvas)',
  surface: 'var(--tt-surface)',
  surfaceMuted: 'var(--tt-surface-muted)',
  border: 'var(--tt-border)',
  borderStrong: 'var(--tt-border-strong)',
  text: 'var(--tt-text)',
  textMuted: 'var(--tt-text-muted)',
  textFaint: 'var(--tt-text-faint)',
  shadowSm: 'var(--tt-shadow-sm)',
  shadowMd: 'var(--tt-shadow-md)',
  radius: 'var(--tt-radius)',
  radiusSm: 'var(--tt-radius-sm)',
  fontDisplay: 'var(--tt-font-display)',
} as const;
