// Styles for the LiveViewPanel component.
// Extracted from the monolithic Dashboard.tsx to keep component files lean.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const liveViewStyles: { [key: string]: any } = {
  liveLayout: {
    display: 'grid',
    gridTemplateColumns: 'minmax(220px, 280px) 1fr',
    gap: 16,
    alignItems: 'stretch',
  },
  liveEmployeeList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
    maxHeight: 480,
    overflowY: 'auto' as const,
    paddingRight: 4,
  },
  emptyText: {
    color: 'var(--tt-text-faint)',
    textAlign: 'center',
    padding: '20px',
  },
  liveEmployeeRow: (selected: boolean, online: boolean) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    textAlign: 'left' as const,
    padding: '12px 14px',
    borderRadius: 14,
    border: selected ? '1px solid var(--tt-ink)' : '1px solid var(--tt-border)',
    backgroundColor: selected ? 'var(--tt-surface-muted)' : 'var(--tt-surface)',
    cursor: 'pointer',
    opacity: online || selected ? 1 : 0.72,
    boxShadow: selected ? 'var(--tt-shadow-sm)' : 'none',
  }),
  statusIndicator: (online: boolean) => ({
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: online ? 'var(--tt-success)' : 'var(--tt-text-faint)',
  }),
  liveEmployeeName: {
    display: 'block',
    fontWeight: 650,
    fontSize: 14,
    color: 'var(--tt-text)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  liveEmployeeMeta: {
    display: 'block',
    fontSize: 11,
    color: 'var(--tt-text-muted)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    marginTop: 2,
  },
  onlineBadge: {
    fontSize: 10,
    fontWeight: 700,
    color: 'var(--tt-success)',
    backgroundColor: 'var(--tt-success-soft)',
    padding: '4px 8px',
    borderRadius: 999,
  },
  offlineBadge: {
    fontSize: 10,
    fontWeight: 700,
    color: 'var(--tt-text-faint)',
    backgroundColor: 'var(--tt-surface-muted)',
    padding: '4px 8px',
    borderRadius: 999,
  },
  liveScreenPanel: {
    border: '1px solid var(--tt-border)',
    borderRadius: 16,
    backgroundColor: 'var(--tt-surface-muted)',
    padding: 16,
    minHeight: 360,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 12,
  },
  liveEmptyScreen: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--tt-text)',
    padding: 24,
    background: 'var(--tt-surface)',
    width: '100%',
    minHeight: 280,
  },
  liveScreenHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap' as const,
  },
  liveScreenTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: 'var(--tt-text)',
  },
  liveScreenSub: {
    fontSize: 12,
    color: 'var(--tt-text-muted)',
    marginTop: 2,
  },
  liveGhostBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid var(--tt-border-strong)',
    background: 'var(--tt-surface)',
    color: 'var(--tt-text)',
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
  },
  livePrimaryBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 12px',
    borderRadius: 8,
    border: 'none',
    background: 'var(--tt-ink)',
    color: '#fff',
    fontSize: 12,
    fontWeight: 600,
  },
  liveQualitySelect: {
    padding: '6px 8px',
    borderRadius: 8,
    border: '1px solid var(--tt-border-strong)',
    background: 'var(--tt-surface)',
    color: 'var(--tt-text)',
    fontSize: 12,
    fontWeight: 600,
  },
  liveMetaRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
    marginBottom: 8,
  },
  liveChip: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '4px 8px',
    borderRadius: 999,
    border: '1px solid var(--tt-border)',
    background: 'var(--tt-surface-2, var(--tt-surface))',
    fontSize: 11,
    color: 'var(--tt-text-muted)',
    fontWeight: 600,
  },
  liveDetails: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 8,
    fontSize: 11,
    color: 'var(--tt-text-muted)',
  },
  liveError: {
    backgroundColor: 'var(--tt-danger-soft)',
    border: '1px solid rgba(232, 93, 76, 0.25)',
    color: 'var(--tt-danger)',
    padding: '8px 10px',
    borderRadius: 8,
    fontSize: 12,
  },
  liveSnapOk: {
    backgroundColor: 'var(--tt-success-soft, rgba(34, 160, 107, 0.12))',
    border: '1px solid rgba(34, 160, 107, 0.28)',
    color: 'var(--tt-success, #1a8f5c)',
    padding: '8px 10px',
    borderRadius: 8,
    fontSize: 12,
  },
  liveScreenStage: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    background: '#111',
    borderRadius: 10,
    overflow: 'hidden',
    minHeight: 280,
    position: 'relative' as const,
  },
  liveScreenStageFullscreen: {
    borderRadius: 0,
    minHeight: '100vh',
    width: '100vw',
    height: '100vh',
    background: '#000',
  },
  liveScreenImage: {
    width: '100%',
    maxHeight: 420,
    objectFit: 'contain' as const,
    display: 'block',
    background: '#111',
  },
  liveScreenImageFullscreen: {
    maxHeight: '100%',
    height: '100%',
    width: '100%',
    background: '#000',
  },
  liveOverlayBar: {
    position: 'absolute' as const,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '10px 14px',
    background: 'linear-gradient(transparent, rgba(0,0,0,0.72))',
    color: '#fff',
    fontSize: 12,
  },
  liveOverlayLive: {
    fontWeight: 700,
    letterSpacing: 0.4,
  },
  liveOverlayBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 36,
    height: 36,
    borderRadius: 8,
    border: '1px solid rgba(255,255,255,0.25)',
    background: 'rgba(0,0,0,0.45)',
    color: '#fff',
    cursor: 'pointer',
  },
  livePrivacyLink: {
    marginTop: 14,
    padding: '8px 14px',
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--tt-teal)',
    background: 'transparent',
    border: '1px solid var(--tt-teal)',
    borderRadius: 6,
    cursor: 'pointer',
  },
};
